/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserLoginHistoryService } from "../userLoginHistory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserLoginHistoryCreateInput } from "./UserLoginHistoryCreateInput";
import { UserLoginHistory } from "./UserLoginHistory";
import { UserLoginHistoryFindManyArgs } from "./UserLoginHistoryFindManyArgs";
import { UserLoginHistoryWhereUniqueInput } from "./UserLoginHistoryWhereUniqueInput";
import { UserLoginHistoryUpdateInput } from "./UserLoginHistoryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserLoginHistoryControllerBase {
  constructor(
    protected readonly service: UserLoginHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserLoginHistory })
  @nestAccessControl.UseRoles({
    resource: "UserLoginHistory",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserLoginHistory(
    @common.Body() data: UserLoginHistoryCreateInput
  ): Promise<UserLoginHistory> {
    return await this.service.createUserLoginHistory({
      data: data,
      select: {
        actions: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserLoginHistory] })
  @ApiNestedQuery(UserLoginHistoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserLoginHistory",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userLoginHistories(
    @common.Req() request: Request
  ): Promise<UserLoginHistory[]> {
    const args = plainToClass(UserLoginHistoryFindManyArgs, request.query);
    return this.service.userLoginHistories({
      ...args,
      select: {
        actions: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        user: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserLoginHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserLoginHistory",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userLoginHistory(
    @common.Param() params: UserLoginHistoryWhereUniqueInput
  ): Promise<UserLoginHistory | null> {
    const result = await this.service.userLoginHistory({
      where: params,
      select: {
        actions: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        user: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserLoginHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserLoginHistory",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserLoginHistory(
    @common.Param() params: UserLoginHistoryWhereUniqueInput,
    @common.Body() data: UserLoginHistoryUpdateInput
  ): Promise<UserLoginHistory | null> {
    try {
      return await this.service.updateUserLoginHistory({
        where: params,
        data: data,
        select: {
          actions: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserLoginHistory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserLoginHistory",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserLoginHistory(
    @common.Param() params: UserLoginHistoryWhereUniqueInput
  ): Promise<UserLoginHistory | null> {
    try {
      return await this.service.deleteUserLoginHistory({
        where: params,
        select: {
          actions: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          user: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
