/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Clinic as PrismaClinic } from "@prisma/client";

export class ClinicServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ClinicCountArgs, "select">): Promise<number> {
    return this.prisma.clinic.count(args);
  }

  async clinics(args: Prisma.ClinicFindManyArgs): Promise<PrismaClinic[]> {
    return this.prisma.clinic.findMany(args);
  }
  async clinic(
    args: Prisma.ClinicFindUniqueArgs
  ): Promise<PrismaClinic | null> {
    return this.prisma.clinic.findUnique(args);
  }
  async createClinic(args: Prisma.ClinicCreateArgs): Promise<PrismaClinic> {
    return this.prisma.clinic.create(args);
  }
  async updateClinic(args: Prisma.ClinicUpdateArgs): Promise<PrismaClinic> {
    return this.prisma.clinic.update(args);
  }
  async deleteClinic(args: Prisma.ClinicDeleteArgs): Promise<PrismaClinic> {
    return this.prisma.clinic.delete(args);
  }
}
